import type { Metadata } from "next";
import { SITE_URL, business } from "./site-data";

// Builds complete, page-unique metadata (title / description / self-
// referencing canonical, plus matching OpenGraph + Twitter tags) so no page
// silently inherits the homepage's og:url or canonical. The OG image itself
// is generated by the file-based app/opengraph-image.tsx route, so no
// `images` field is set here.
export function pageMetadata({
  title,
  description,
  path,
  titleTemplate,
}: {
  title: string;
  description: string;
  path: string;
  // Pass false to use the exact title as-is, bypassing the root layout's
  // "%s | Groomer On Call" template. Used by the homepage only.
  titleTemplate?: false;
}): Metadata {
  const url = `${SITE_URL}${path === "/" ? "" : path}`;
  const fullTitle = titleTemplate === false ? title : `${title} | ${business.name}`;

  return {
    // A bare string title still gets the root layout's template applied, so
    // opting out requires the `{ absolute }` form — otherwise the business
    // name would be appended twice on the homepage.
    title: titleTemplate === false ? { absolute: fullTitle } : title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      siteName: business.name,
      title: fullTitle,
      description,
      url,
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
    },
  };
}
