const fs = require('fs');
const path = require('path');

const services = [
  ['dog-grooming.html','Dog Grooming'], ['cat-grooming.html','Cat Grooming'], ['puppy-grooming.html','Puppy Grooming'], ['bath-and-brush.html','Bath & Brush'],
  ['deshedding.html','Deshedding'], ['nail-trims.html','Nail Trims'], ['dog-daycare.html','Dog Daycare'], ['overnight-stays.html','Overnight Stays']
];
const areas = [['el-paso.html','El Paso'],['west-el-paso.html','West El Paso'],['northwest-el-paso.html','Northwest El Paso'],['upper-valley.html','Upper Valley'],['canutillo.html','Canutillo'],['sunland-park.html','Sunland Park']];
const phone = '+19154075512';
const serviceDropdown = prefix => services.map(([file,label]) => `<a href="${prefix}services/${file}">${label}</a>`).join('');
const areaDropdown = prefix => areas.map(([file,label]) => `<a href="${prefix}service-areas/${file}">${label}</a>`).join('');
const nav = prefix => `<nav class="main-nav" aria-label="Main navigation"><a href="${prefix}index.html">Home</a><details class="nav-menu"><summary>Services <span>+</span></summary><div class="dropdown"><p>Care, always personalized</p>${serviceDropdown(prefix)}<a class="all-link" href="${prefix}services/index.html">View all services →</a></div></details><details class="nav-menu"><summary>Service Areas <span>+</span></summary><div class="dropdown area-dropdown"><p>Visit us in west El Paso</p>${areaDropdown(prefix)}<a class="all-link" href="${prefix}service-areas/index.html">All service areas →</a></div></details><a href="${prefix}index.html#reviews">Reviews</a><a href="${prefix}index.html#location">Contact</a><details class="mobile-menu"><summary>Menu <span>☰</span></summary><div class="mobile-dropdown"><a href="${prefix}index.html">Home</a><a href="${prefix}services/index.html">All services</a>${serviceDropdown(prefix)}<a href="${prefix}service-areas/index.html">Service areas</a>${areaDropdown(prefix)}<a href="${prefix}index.html#reviews">Reviews</a><a href="${prefix}index.html#location">Contact</a></div></details><a href="${prefix}index.html#reservation" class="call">Book now <b>↗</b></a></nav>`;
const booking = (prefix='') => `<section class="reservation" id="reservation"><div class="reservation-copy"><p class="tag">Let's meet</p><h2>Make a reservation.</h2><p class="booking-note"><strong>Please note:</strong> This is a request for an appointment, not an appointment. We will contact you to confirm. Thank you!</p><p>Choose a date first, then pick a time. Your contact details appear after you have selected your time.</p><div class="reservation-points"><span>Grooming</span><span>Daycare</span><span>Spa treatment</span></div></div><form class="booking-form schedule-form" data-booking-form><div class="form-top"><p>Choose your visit</p><span>Step 1 of 2</span></div><div class="calendar-choice" data-calendar><span class="field-label">1. Pick a date</span><input type="hidden" name="date" data-calendar-input><div class="calendar-shell"><div class="calendar-head"><button type="button" data-calendar-prev aria-label="Previous month">&#8592;</button><strong data-calendar-month></strong><button type="button" data-calendar-next aria-label="Next month">&#8594;</button></div><div class="calendar-days" aria-hidden="true"><span>Sun</span><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span></div><div class="calendar-grid" data-calendar-grid></div></div></div><div class="time-choice" data-time-slots hidden><span class="field-label">2. Pick a time</span><input type="hidden" name="time" data-time-input><div class="time-slots"><button type="button" data-time="9:00 am - 11:00 am">9:00 am - 11:00 am</button><button type="button" data-time="11:00 am - 1:00 pm">11:00 am - 1:00 pm</button><button type="button" data-time="1:00 pm - 2:00 pm">1:00 pm - 2:00 pm</button></div></div><div class="schedule-details" data-schedule-details hidden><div class="form-divider"><span>Step 2 of 2</span><strong>Tell us about the visit</strong></div><div class="two-col"><label>Pet<select name="pet_type"><option>Dog</option><option>Cat</option></select></label><label>Interested in<select required name="service"><option value="">Choose a service</option><option>Full Service</option><option>Nail Trim</option><option>Buffing</option><option>Daycare</option><option>Spa Treatment</option><option>Other</option></select></label></div><label>Pet name<input required name="pet_name" autocomplete="off" placeholder="Your pet's name"></label><div class="two-col"><label>Name<input required name="name" autocomplete="name" placeholder="First and last name"></label><label>Email<input required name="email" type="email" autocomplete="email" placeholder="you@email.com"></label></div><label>Phone<input required name="phone" type="tel" autocomplete="tel" placeholder="(915) 000-0000"></label><label>Message<textarea name="message" rows="3" placeholder="Anything we should know?"></textarea></label><button class="button orange" type="submit">Send reservation request <span>&#8594;</span></button><p class="form-response" role="status"></p></div></form></section>`;
const homeStory = `<section class="original-gallery" aria-label="Happy Petssible visitors"><figure><img src="assets/puppy01-1536x1536%20-%20Copy.png" alt="Fluffy puppy after a Petssible visit"></figure><figure><img src="assets/puppy02.png" alt="Pug at Petssible"></figure><figure><img src="assets/puppy03-1536x1536.png" alt="Beagle puppy at Petssible"></figure><figure><img src="assets/puppy04%20-%20Copy.png" alt="Terrier puppy at Petssible"></figure></section><section class="intro-story"><div class="story-mark">care<br>is<br>real</div><div><p class="tag">Happy pets, happy humans</p><h2>Every good groom starts with a pet who feels understood.</h2><p>Pets are family. At Petssible, we build every visit around comfort, patience, and the small details that make a difference, whether your pet is here for a fresh cut, a nail trim, a play day, or an overnight stay.</p><p>Our El Paso team is here to create a clean, playful, and safe experience for pets and the people who love them.</p><a class="text-link" href="#reservation">Start a visit with Petssible &#8594;</a></div></section><section class="original-highlights"><p class="tag">We are best in</p><div><span>Grooming</span><span>Spa treatment</span><span>Nail trim</span><span>Daycare</span><span>Pick up</span><span>Paw balm</span></div></section><section class="care-pillars"><article><span>01</span><h3>Gentle handling</h3><p>We take time to help each pet settle in before care begins.</p></article><article><span>02</span><h3>Clear communication</h3><p>We listen to what you want and explain the next step.</p></article><article><span>03</span><h3>Tailored care</h3><p>Every coat, routine, and comfort level deserves its own approach.</p></article></section>`;
const homeLocation = `<section class="location-section" id="location"><div><p class="tag">Visit Petssible</p><h2>Right here when your pet needs us.</h2><p class="location-address">369 Shadow Mountain Dr Ste B<br>El Paso, TX 79912</p><p>Monday to Friday, 8 AM–5 PM<br>Saturday, 9 AM–6 PM</p><div class="actions"><a class="button dark" href="https://www.google.com/maps/search/?api=1&query=369%20Shadow%20Mountain%20Dr%20Ste%20B%2C%20El%20Paso%2C%20TX%2079912">Get directions</a><a class="button outline" href="tel:${phone}">Call (915) 407-5512</a></div></div><div class="location-image"><img src="assets/puppy04%20-%20Copy.png" alt="A bright-eyed dog at Petssible"></div></section><section class="home-faq"><p class="tag">Good to know</p><h2>A few questions pet parents ask.</h2><details><summary>What time should I drop off my dog for daycare?</summary><p>To help establish group play, Petssible asks for dog drop-off by 9 AM. Call ahead to ask about an exit bath or a different schedule.</p></details><details><summary>What should I bring for daycare?</summary><p>Something that smells like home, such as a blanket, T-shirt, or even a sock, can help your dog feel more comfortable while away from you.</p></details><details><summary>How old does my dog have to be?</summary><p>For most dog-care settings, puppies need their first round of adult shots. Call Petssible so the team can advise based on your pet and the service you need.</p></details></section>`;
const serviceExtra = `<section class="service-extra"><p class="tag">Before you visit</p><h2>Small details make for a smoother appointment.</h2><div class="three-notes"><article><span>01</span><h3>Share your pet’s needs</h3><p>Let us know about any sensitivities, coat concerns, or routines that help your pet feel settled.</p></article><article><span>02</span><h3>Bring the basics</h3><p>Call before your visit if you have questions about items, records, or timing for your selected service.</p></article><article><span>03</span><h3>Keep the conversation open</h3><p>We are here to listen. Ask about your pet’s care and tell us what a great visit looks like to you.</p></article></div></section>`;
const areaExtra = `<section class="area-extra"><p class="tag">A familiar place for your pet</p><h2>Worth the visit from around El Paso.</h2><p>Petssible is based on Shadow Mountain Drive, an easy home base for pet families on the west side and nearby communities. Rather than promising a generic service radius, these pages are here to help you find the care you need and plan a visit with our team.</p><a class="button orange" href="../index.html#reservation">Request an appointment</a></section>`;
const nativeGallery = `<section class="native-gallery"><div class="native-gallery-intro"><p class="tag">Fresh from the grooming table</p><h2>Real Petssible guests, looking their best.</h2><p>These are real photos from Petssible grooming visits. Every coat, comfort level, and finish is different.</p></div><div class="native-gallery-grid"><figure><img src="assets/petssible-groomed-poodle.jpg" alt="Freshly groomed poodle at Petssible in El Paso"></figure><figure><img src="assets/petssible-groomed-spaniel.jpg" alt="Freshly groomed dog at Petssible in El Paso"></figure><figure><img src="assets/petssible-groomed-pomeranian.jpg" alt="Freshly groomed Pomeranian at Petssible in El Paso"></figure><figure><img src="assets/petssible-groomed-terrier.jpg" alt="Freshly groomed terrier at Petssible in El Paso"></figure></div></section>`;
const quoteModal = `<div class="quote-modal" data-quote-modal hidden><div class="quote-backdrop" data-quote-close></div><section class="quote-panel" role="dialog" aria-modal="true" aria-labelledby="quote-title"><button class="quote-close" type="button" aria-label="Close quote form" data-quote-close>&times;</button><p class="tag">Petssible</p><h2 id="quote-title">Get a quote</h2><p>Tell us a little about your pet and the service you need. The Petssible team will follow up with you.</p><form data-quote-form><label>First name<input required name="first_name" autocomplete="given-name" placeholder="Your first name"></label><label>Pet name<input required name="pet_name" autocomplete="off" placeholder="Your pet's name"></label><label>Service<select required name="service"><option value="">Choose a service</option><option>Full Service</option><option>Nail Trim</option><option>Buffing</option><option>Daycare</option><option>Spa Treatment</option><option>Other</option></select></label><label>Message<textarea name="message" rows="4" placeholder="Tell us what your pet needs"></textarea></label><button class="button orange" type="submit">Request a quote &#8594;</button><p class="form-response" role="status"></p></form></section></div>`;
function change(file) {
  const isHome = path.basename(file) === 'index.html' && path.dirname(file).endsWith('petssible-seo');
  const inSubdir = !isHome && path.dirname(file) !== path.resolve(path.dirname(file),'..');
  const prefix = isHome ? '' : '../';
  let html = fs.readFileSync(file,'utf8');
  html = html.replace('<link rel="stylesheet" href="' + prefix + 'enhancements.css">', '<link rel="stylesheet" href="' + prefix + 'enhancements.css"><link rel="stylesheet" href="' + prefix + 'mobile.css"><link rel="stylesheet" href="' + prefix + 'calendar.css"><link rel="stylesheet" href="' + prefix + 'original-tuning.css"><link rel="stylesheet" href="' + prefix + 'blog.css"><link rel="stylesheet" href="' + prefix + 'quote.css"><link rel="stylesheet" href="' + prefix + 'stickers.css">');
  html = html.replace(/<nav>.*?<\/nav>/, nav(prefix));
  html = html.replace(`<a href="${prefix}index.html#reviews">Reviews</a>`, `<a href="${prefix}blog/index.html">Blog</a><a href="${prefix}index.html#reviews">Reviews</a>`);
  html = html.replace(/<h1>Care is <em>Real<\/em><\/h1>/, '<h1>Care is <em>Real</em><span class="seo-h1">Pet Grooming, Spa &amp; Daycare in El Paso, TX</span></h1>');
  if (isHome) html = html.replace('<div class="actions"><a class="button dark" href="services/index.html">Explore services</a><a class="button orange" href="tel:+19154075512">Book by phone</a></div>', '<div class="actions"><a class="button dark" href="tel:+19154075512">Call (915) 407-5512</a><a class="button orange" href="#quote-form" data-quote-trigger>Get a quote</a></div>');
  if (isHome) html = html.replace('<img class="hero-dog" src="assets/iStock-157527277.webp" alt="Happy dog at Petssible">', '<div class="hero-stickers" aria-hidden="true"><span class="hero-sticker goldendoodle"><img src="assets/goldendoodle_border.png" alt=""></span><span class="hero-sticker chihuahua"><img src="assets/iStock-462392661.webp" alt=""></span></div><img class="hero-dog" src="assets/iStock-157527277.webp" alt="Happy dog at Petssible">');
  html = html.replace(/<a class="button orange" href="[^"]*#reservation">Get a quote<\/a>/g, '<a class="button orange" href="#quote-form" data-quote-trigger>Get a quote</a>');
  html = html.replace('<footer>', `${quoteModal}<footer>`);
  if (isHome) {
    html = html.replace('<section class="section"><p class="tag">Pet care, made personal</p>', `${homeStory}<section class="section"><p class="tag">Pet care, made personal</p>`);
    html = html.replace('<section class="reviews-section" id="reviews">', `${booking()}<section class="reviews-section" id="reviews">`);
    html = html.replace('<section class="reviews-section" id="reviews">', `${nativeGallery}<section class="reviews-section" id="reviews">`);
    html = html.replace('<section class="contact">', `${homeLocation}<section class="home-faq faq-more"><p class="tag">More answers</p><h2>Planning your pet's visit.</h2><details><summary>Do you groom cats?</summary><p>Yes. Petssible offers cat grooming. Tell us a little about your cat when you request an appointment so the team can help plan the visit.</p></details><details><summary>Do I need an appointment for a nail trim?</summary><p>Please request a visit or call Petssible first. The team can confirm the right time and help keep your pet's wait as calm as possible.</p></details><details><summary>Where is Petssible located?</summary><p>We are at 369 Shadow Mountain Dr Ste B in El Paso, Texas. Use the directions link or call (915) 407-5512 if you need help finding us.</p></details></section><section class="contact">`);
  } else if (file.includes(`${path.sep}services${path.sep}`) && !file.endsWith(`${path.sep}services${path.sep}index.html`)) {
    html = html.replace('<section class="faq">', `${serviceExtra}${booking('../')}<section class="faq">`);
  } else if (file.includes(`${path.sep}service-areas${path.sep}`) && !file.endsWith(`${path.sep}service-areas${path.sep}index.html`)) {
    html = html.replace('<section class="section"><p class="tag">Explore nearby</p>', `${areaExtra}<section class="section"><p class="tag">Explore nearby</p>`);
  }
  fs.writeFileSync(file,html);
}
module.exports = out => {
  const folders = [out,path.join(out,'services'),path.join(out,'service-areas'),path.join(out,'blog')];
  folders.flatMap(folder => fs.readdirSync(folder).filter(x=>x.endsWith('.html')).map(x=>path.join(folder,x))).forEach(change);
};
