const fs = require('fs');
const path = require('path');

const out = path.resolve(__dirname, '..', '..', 'outputs', 'petssible-seo');
const business = {
  name: 'PETSSIBLE | Pet Grooming', short: 'Petssible', domain: 'https://petssibleus.com',
  phone: '(915) 407-5512', tel: '+19154075512', street: '369 Shadow Mountain Dr Ste B', city: 'El Paso', state: 'TX', zip: '79912',
  rating: '4.8', reviewCount: '141', hours: 'Mon-Fri 8:00 AM-5:00 PM, Sat 9:00 AM-6:00 PM',
  description: 'Professional dog and cat grooming, spa care, daycare, and overnight stays in El Paso, Texas.'
};
const services = [
  ['dog-grooming','Dog Grooming','Professional Dog Grooming in El Paso, TX','A complete grooming visit shaped around your dog, from a careful bath and blow-dry to coat care, trimming, and a clean finish.','Dog grooming appointments in El Paso with a patient, caring approach for every coat type and size.'],
  ['cat-grooming','Cat Grooming','Cat Grooming in El Paso, TX','For cats who need a bath, deshedding, nail trim, or haircut, ask about cat appointments. Reviews mention cat-grooming availability on Thursdays and Saturdays, so please call to confirm the current schedule.','Gentle cat grooming in El Paso, including bathing, deshedding, nail trims, and coat care.'],
  ['puppy-grooming','Puppy Grooming','Puppy Grooming in El Paso, TX','A first grooming visit can set the tone for a lifetime of comfortable care. We take time to help puppies settle in and get familiar with grooming.','A calm, patient introduction to puppy grooming in El Paso.'],
  ['bath-and-brush','Bath & Brush','Dog Bath and Brush Service in El Paso, TX','A bath and brush service is ideal between full grooms or when your dog needs to come home fresh, soft, and comfortable.','Bath, brush, drying, and coat refresh appointments for dogs in El Paso.'],
  ['deshedding','Deshedding','Dog and Cat Deshedding in El Paso, TX','Seasonal shedding can be a lot to manage. A focused deshedding visit helps lift loose coat while keeping your pet comfortable.','Deshedding services in El Paso for pets with heavy or seasonal coat shedding.'],
  ['nail-trims','Nail Trims','Pet Nail Trims in El Paso, TX','Quick nail care matters, especially for pets who are nervous about paws. Reviews specifically mention patient nail trims and pet-safe nail polish.','Gentle nail trim appointments for dogs and cats in El Paso.'],
  ['dog-daycare','Dog Daycare','Dog Daycare in El Paso, TX','Give your dog a supervised place to spend the day while you are away. Call us to discuss availability, your dog’s needs, and a first visit.','Dog daycare in El Paso with care, attention, and a pet-friendly environment.'],
  ['overnight-stays','Overnight Stays','Overnight Dog Stays in El Paso, TX','When you need overnight care, Petssible offers a familiar place for your dog. Contact us to discuss dates, routines, and availability.','Overnight stays and pet care options in El Paso, Texas.']
].map(([slug,name,h1,hero,desc]) => ({slug,name,h1,hero,desc}));
const areas = [
  ['el-paso','El Paso','Pet Grooming in El Paso, TX'], ['west-el-paso','West El Paso','Pet Grooming Near West El Paso, TX'],
  ['northwest-el-paso','Northwest El Paso','Pet Grooming Near Northwest El Paso, TX'], ['upper-valley','Upper Valley','Pet Grooming Near the Upper Valley, El Paso'],
  ['canutillo','Canutillo','Pet Grooming Near Canutillo, TX'], ['sunland-park','Sunland Park','Pet Grooming Near Sunland Park, NM']
].map(([slug,name,h1]) => ({slug,name,h1}));
const blogs = [
  {slug:'dog-grooming-frequency',title:'How Often Should You Groom Your Dog?',meta:'Dog Grooming Frequency Guide | Petssible',desc:'A practical guide to grooming frequency for dogs in El Paso, including coat, lifestyle, and comfort factors.',body:`<p>There is no single grooming schedule that fits every dog. Coat type, activity level, shedding, and home care all influence how often your dog may need a professional visit. A short-haired dog may only need occasional bathing and nail care, while a curly or long-coated dog can benefit from regular brushing and trims.</p><h2>Start with your dog’s coat and routine</h2><p>Dogs with coats that mat easily need attention before tangles become uncomfortable. Regular brushing at home helps, and a grooming team can talk through a sensible schedule based on what they see in your dog’s coat. Active dogs may also need baths more often than dogs who stay mostly indoors.</p><h2>Do not overlook nails and skin</h2><p>Nail trims are part of comfort, not just appearance. If you hear nails clicking on the floor, it may be time to ask about a trim. If your dog has skin sensitivity, coat changes, or a grooming concern, share it before the visit so the team can plan with care.</p><p>Petssible offers dog grooming, bath and brush visits, deshedding, and nail trims in El Paso. Call or send a request when you are ready to talk through your dog’s routine.</p>`},
  {slug:'prepare-for-dog-grooming',title:'How to Prepare for a Dog Grooming Visit',meta:'Prepare for Dog Grooming | Petssible',desc:'Simple ways El Paso pet parents can prepare their dog for a calm, comfortable grooming visit.',body:`<p>A relaxed grooming visit begins before your dog arrives. A little preparation can help the team understand your dog, make check-in easier, and support a calmer experience for everyone.</p><h2>Share the important details</h2><p>Tell the groomer about your dog’s coat, sensitivities, previous grooming experiences, and the style you want. If there is a particular area your dog dislikes being touched, mention it early. Clear communication helps the team shape the visit around your pet.</p><h2>Plan the day around your pet</h2><p>Give your dog a chance to use the restroom and arrive with a little time to settle. Bring any information the team requested, and make sure your phone number is current. For puppies or nervous pets, an early positive experience matters more than rushing a complicated haircut.</p><p>Petssible serves dogs and cats from El Paso and nearby communities. Use the appointment request form to select a preferred time, then add the details that will help the team prepare.</p>`},
  {slug:'when-your-dog-needs-deshedding',title:'When Does a Dog Need Deshedding?',meta:'When Your Dog Needs Deshedding | Petssible',desc:'Signs that your dog may benefit from professional deshedding and a coat-care visit in El Paso.',body:`<p>Shedding can be part of everyday life with a dog, but excess loose coat can make your home, furniture, and dog less comfortable. A deshedding visit focuses on lifting loose undercoat and refreshing the coat with the right bath, drying, and brushing process.</p><h2>Common signs it is time</h2><p>Fur collecting around the house, a dull-looking coat, or more loose hair after brushing can all be signs that your dog needs extra coat care. Seasonal changes can make the issue more noticeable. A professional can help decide whether deshedding, a bath and brush, or a full grooming visit makes the most sense.</p><h2>Keep home care simple</h2><p>Between visits, use a brush suited to your dog’s coat and keep the routine gentle. Avoid pulling at mats or using tools that may irritate the skin. If you are unsure what your dog needs, call Petssible before booking.</p><p>Petssible offers deshedding services in El Paso, plus bath and brush care for dogs who need a coat refresh.</p>`},
  {slug:'dog-daycare-checklist',title:'Dog Daycare Checklist for El Paso Pet Parents',meta:'Dog Daycare Checklist in El Paso | Petssible',desc:'What to consider before your dog’s first daycare visit, from drop-off timing to familiar comfort items.',body:`<p>Daycare can give social dogs a structured place to play, rest, and spend the day while their people are away. Before a first visit, it helps to share your dog’s routine and ask the team about current availability and requirements.</p><h2>Plan the first drop-off</h2><p>Petssible asks for daycare drop-off by 9 AM to help establish group play. If you need a different schedule or want to ask about an exit bath, call ahead. This gives the team time to plan the best experience for your dog.</p><h2>Bring a familiar comfort item</h2><p>A blanket, T-shirt, or another item that smells like home may help your dog feel settled. Ask the team what is appropriate for your pet’s visit. Share any feeding, medication, or behavior details before you arrive.</p><p>For dog daycare in El Paso, use Petssible’s scheduling form to request a preferred date and time, or call the team to talk through your dog’s first visit.</p>`}
];
const reviews = [
  ['Stacie Lopez','5 months ago','I had such a great experience at Petssible Pet Grooming! From scheduling the appointment to drop-off and pick-up, everything was smooth and easy. My doggy Coco was a little nervous at drop-off, but she was so happy when I picked her up. She came home clean, fluffy, shiny, and smelling amazing. We will definitely be coming back!'],
  ['selena pedroza','4 months ago','Went to take my little one to get her nails clipped and they went above and beyond to make her feel comfortable and even painted her nails with pet safe nail polish. She looks so adorable. Cynthia did a great job'],
  ['Hailey Hindman','4 weeks ago','My puppy went in looking a wreck, and when I picked him up, he looked like a whole new puppy! So fluffy and cute! I absolutely loved how his groom turned out! And the ladies there were all so kind and hospitable! Don’t see any reason not to be a regular! Thank you!'],
  ['Bianca Gurrola','4 months ago','The staff at Petssible are great. They make sure the pups are comfortable before they work on them. My baby looks adorable after her grooming session. Thank you so much Fabiola, you have made a repeat customer out of me and Maple.'],
  ['Sebastian Carbonell','4 months ago','Fabiola did a tremendous job grooming my dog! She has so much patience and handled him so carefully and gently the entire time. She listened to exactly how I wanted his haircut and delivered it perfectly.'],
  ['Vanessa Quinones','5 months ago','Amazing service! I love how they treated my puppy as it was her first time getting groomed, especially the worker named Cassandra. Overall amazing work and hope they keep it up. For sure will be back!']
].map(([name,date,text]) => ({name,date,text}));

const esc = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const dirs = 'https://www.google.com/maps/search/?api=1&query=' + encodeURIComponent(`${business.street}, ${business.city}, ${business.state} ${business.zip}`);
const google = 'https://www.google.com/search?q=pettsible+pet+grooming';
const href = (depth, value) => `${'../'.repeat(depth)}${value}`;
const serviceLinks = depth => services.map(s => `<a href="${href(depth,`services/${s.slug}.html`)}">${esc(s.name)}</a>`).join('');
const areaLinks = depth => areas.map(a => `<a href="${href(depth,`service-areas/${a.slug}.html`)}">${esc(a.name)}</a>`).join('');
function ld(extra = {}) { return JSON.stringify({ '@context':'https://schema.org', '@graph': [
  {'@type':'LocalBusiness','@id':`${business.domain}/#business`,name:business.name,url:business.domain,telephone:business.tel,description:business.description,
    address:{'@type':'PostalAddress',streetAddress:business.street,addressLocality:business.city,addressRegion:business.state,postalCode:business.zip,addressCountry:'US'},
    openingHoursSpecification:[{'@type':'OpeningHoursSpecification',dayOfWeek:['Monday','Tuesday','Wednesday','Thursday','Friday'],opens:'08:00',closes:'17:00'},{'@type':'OpeningHoursSpecification',dayOfWeek:'Saturday',opens:'09:00',closes:'18:00'}],
    aggregateRating:{'@type':'AggregateRating',ratingValue:business.rating,reviewCount:business.reviewCount,bestRating:'5'},
    review:reviews.map(r=>({'@type':'Review',author:{'@type':'Person',name:r.name},reviewBody:r.text,reviewRating:{'@type':'Rating',ratingValue:'5',bestRating:'5'}}))},
  {'@type':'WebSite','@id':`${business.domain}/#website`,url:business.domain,name:business.short}, extra
]}); }
function shell({title,description,body,depth=0,extra={},pagePath=''}) { const base = href(depth,''); return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${business.domain}/${pagePath}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:image" content="${business.domain}/assets/iStock-157527277.webp"><link rel="stylesheet" href="${base}site.css"><link rel="stylesheet" href="${base}enhancements.css"><script type="application/ld+json">${ld(extra)}</script></head><body><div class="topbar"><a href="${dirs}">${esc(business.street)}, ${business.city}, ${business.state} ${business.zip}</a><span>${business.hours}</span><a href="${google}">Google rating ${business.rating}/5 (${business.reviewCount})</a></div><header><a class="logo" href="${base}index.html"><img src="${base}assets/main_logo@2x-1280x621.png" alt="Petssible"></a><nav><a href="${base}index.html">Home</a><a href="${base}services/index.html">Services</a><a href="${base}service-areas/index.html">Service Areas</a><a href="${base}index.html#reviews">Reviews</a><a href="tel:${business.tel}" class="call">Call ${business.phone}</a></nav></header>${body}<footer><img src="${base}assets/main_logo@2x-1280x621.png" alt="Petssible"><p>${esc(business.description)}</p><p><a href="tel:${business.tel}">${business.phone}</a> · <a href="${dirs}">${esc(business.street)}, El Paso, TX</a></p><div>${serviceLinks(depth)}${areaLinks(depth)}</div><small>© 2026 Petssible. All rights reserved.</small></footer><script src="${base}site.js"></script></body></html>`; }
function card(s,depth) { return `<article class="card"><p class="tag">Petssible service</p><h3>${esc(s.name)}</h3><p>${esc(s.desc)}</p><a href="${href(depth,`services/${s.slug}.html`)}">Explore ${esc(s.name)} <b>→</b></a></article>`; }
function home() { const reviewCards=reviews.slice(0,3).map(r=>`<article class="review"><p class="stars" aria-label="5 out of 5 stars">★★★★★</p><blockquote>“${esc(r.text)}”</blockquote><p><strong>${esc(r.name)}</strong><br><span>Google review · ${esc(r.date)}</span></p></article>`).join(''); return shell({title:'Pet Grooming in El Paso, TX | Petssible',description:'Petssible offers caring dog and cat grooming, spa care, daycare, and overnight stays in El Paso, Texas.',pagePath:'',body:`<main><section class="hero"><div class="hero-copy"><p class="tag">El Paso pet care</p><h1>Care is <em>Real</em></h1><p>Professional and caring grooming and spa services for dogs and cats in El Paso.</p><div class="actions"><a class="button dark" href="services/index.html">Explore services</a><a class="button orange" href="tel:${business.tel}">Book by phone</a></div></div><img class="hero-dog" src="assets/iStock-157527277.webp" alt="Happy dog at Petssible"></section><section class="rating-band"><p><strong>${business.rating} out of 5</strong> from <strong>${business.reviewCount} Google reviews</strong></p><a href="${google}">Read our Google reviews</a></section><section class="section"><p class="tag">Pet care, made personal</p><h2>Services for clean coats, comfortable paws, and happy pets.</h2><div class="grid">${services.map(s=>card(s,0)).join('')}</div><p class="center"><a class="text-link" href="services/index.html">View all grooming and care services →</a></p></section><section class="reviews-section" id="reviews"><p class="tag">Real client feedback</p><h2>Kind words from pet parents.</h2><div class="review-grid">${reviewCards}</div><p class="center"><a class="button orange" href="${google}">See all Google reviews</a></p></section><section class="section areas"><div><p class="tag">Serving the El Paso region</p><h2>Pet owners visit us from El Paso and nearby communities.</h2><p>Our shop is at ${esc(business.street)} in El Paso. Browse our local service-area pages for grooming information close to home.</p><a class="button dark" href="service-areas/index.html">Explore service areas</a></div><img src="assets/goldendoodle_border.png" alt="Goldendoodle at Petssible"></section><section class="contact"><p class="tag">Ready to book?</p><h2>Call Petssible to discuss your pet’s visit.</h2><p>${esc(business.phone)} · ${business.hours}</p><a class="button orange" href="tel:${business.tel}">Call ${business.phone}</a></section></main>`}); }
function servicePage(s) { const faq=[['What is included?','Every pet has different coat, skin, and comfort needs. Call Petssible so the team can recommend the right service for your pet.'],['Do I need an appointment?','Please call ahead to discuss availability and book a visit.'],['Where are you located?',`Petssible is located at ${business.street}, ${business.city}, ${business.state} ${business.zip}.`]]; return shell({depth:1,title:`${s.h1} | Petssible`,description:s.desc,pagePath:`services/${s.slug}.html`,extra:{'@type':'Service',name:s.name,provider:{'@id':`${business.domain}/#business`},areaServed:business.city},body:`<main><section class="subhero"><p class="crumb"><a href="../index.html">Home</a> / <a href="index.html">Services</a> / ${esc(s.name)}</p><h1>${esc(s.h1)}</h1><p>${esc(s.hero)}</p><div class="actions"><a class="button orange" href="tel:${business.tel}">Call to book</a><a class="button outline" href="../service-areas/index.html">Areas we serve</a></div></section><section class="content-wrap"><article><h2>${esc(s.name)} with a caring approach</h2><p>${esc(s.hero)} Petssible focuses on a clean, welcoming environment and takes time to understand your pet’s needs before the visit.</p><h2>Plan your pet’s appointment</h2><p>Call ${business.phone} to ask about timing, preparation, and availability. The team can also help you choose between related services such as bath and brush care, deshedding, or nail trims.</p><div class="link-list"><h3>Related Petssible services</h3>${services.filter(x=>x.slug!==s.slug).slice(0,4).map(x=>`<a href="${x.slug}.html">${esc(x.name)} →</a>`).join('')}</div></article><aside><p class="tag">Petssible</p><h3>Book ${esc(s.name)}</h3><p>${esc(business.street)}<br>El Paso, TX ${business.zip}</p><a class="button dark" href="tel:${business.tel}">Call ${business.phone}</a></aside></section><section class="faq"><p class="tag">Questions</p><h2>${esc(s.name)} FAQs</h2>${faq.map(([q,a])=>`<details><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('')}</section><section class="contact"><h2>Looking for ${esc(s.name)} near you?</h2><p>See the nearby communities Petssible serves, then call to discuss your visit.</p><a class="button orange" href="../service-areas/index.html">Explore service areas</a></section></main>`}); }
function areaPage(a) { return shell({depth:1,title:`${a.h1} | Petssible`,description:`Pet owners from ${a.name} visit Petssible in El Paso for caring grooming, spa care, nail trims, daycare, and overnight stays.`,pagePath:`service-areas/${a.slug}.html`,extra:{'@type':'Service',name:`Pet grooming for ${a.name}`,provider:{'@id':`${business.domain}/#business`},areaServed:a.name},body:`<main><section class="subhero"><p class="crumb"><a href="../index.html">Home</a> / <a href="index.html">Service Areas</a> / ${esc(a.name)}</p><h1>${esc(a.h1)}</h1><p>Pet owners from ${esc(a.name)} visit Petssible at ${esc(business.street)} in El Paso for attentive, professional pet care.</p><div class="actions"><a class="button orange" href="tel:${business.tel}">Call to book</a><a class="button outline" href="${dirs}">Get directions</a></div></section><section class="content-wrap"><article><h2>A pet groomer near ${esc(a.name)}</h2><p>When you are looking for a groomer near ${esc(a.name)}, Petssible offers a welcoming destination in El Paso for dogs and cats. Call ahead and the team can help plan the right visit for your pet, from routine grooming to nail care and deshedding.</p><h2>Services pet parents ask about</h2><p>Choose a <a href="../services/dog-grooming.html">dog grooming</a>, <a href="../services/cat-grooming.html">cat grooming</a>, <a href="../services/bath-and-brush.html">bath and brush</a>, or <a href="../services/nail-trims.html">nail trim</a> visit. For care beyond the grooming table, ask about <a href="../services/dog-daycare.html">daycare</a> and <a href="../services/overnight-stays.html">overnight stays</a>.</p><h2>Visit Petssible in El Paso</h2><p>Our address is ${esc(business.street)}, El Paso, TX ${business.zip}. Call ${business.phone} to confirm appointment availability and talk through your pet’s needs.</p></article><aside><p class="tag">Visit Petssible</p><h3>From ${esc(a.name)}</h3><p>${esc(business.street)}<br>El Paso, TX ${business.zip}</p><a class="button dark" href="${dirs}">Get directions</a></aside></section><section class="section"><p class="tag">Explore nearby</p><h2>Other Petssible service areas</h2><div class="area-chips">${areas.filter(x=>x.slug!==a.slug).map(x=>`<a href="${x.slug}.html">${esc(x.name)}</a>`).join('')}</div></section></main>`}); }
function listing(kind) { const isServices=kind==='services'; const collection=isServices?services:areas; const title=isServices?'Pet Grooming and Pet Care Services in El Paso, TX':'Pet Grooming Service Areas Near El Paso, TX'; const desc=isServices?'Explore Petssible grooming, bath, nail care, daycare, and overnight stay services in El Paso.':'Explore local areas where pet owners visit Petssible for professional grooming and pet care.'; const cards=collection.map(x=>`<article class="card"><p class="tag">${isServices?'Petssible service':'Service area'}</p><h3>${esc(x.name)}</h3><p>${esc(isServices?x.desc:`Pet owners from ${x.name} visit Petssible in El Paso for professional grooming and pet care.`)}</p><a href="${x.slug}.html">Learn more <b>→</b></a></article>`).join(''); return shell({depth:1,title,description:desc,pagePath:isServices?'services/':'service-areas/',body:`<main><section class="subhero"><p class="crumb"><a href="../index.html">Home</a> / ${isServices?'Services':'Service Areas'}</p><h1>${esc(title)}</h1><p>${esc(desc)}</p></section><section class="section"><div class="grid">${cards}</div></section><section class="contact"><h2>Need help choosing a service?</h2><p>Call Petssible at ${business.phone} and the team can help.</p><a class="button orange" href="tel:${business.tel}">Call now</a></section></main>`}); }
function markdown(title,desc,url) { return `# ${title}\n\n${desc}\n\n- Business: ${business.name}\n- Phone: ${business.phone}\n- Address: ${business.street}, ${business.city}, ${business.state} ${business.zip}\n- URL: ${business.domain}/${url}\n`; }
function blogIndex() { return shell({depth:1,title:'Pet Grooming Tips in El Paso | Petssible',description:'Helpful Petssible articles about dog grooming, deshedding, daycare, and preparing pets for care in El Paso.',pagePath:'blog/',body:`<main><section class="subhero"><p class="crumb"><a href="../index.html">Home</a> / Pet Care Blog</p><h1>Pet care tips for El Paso families.</h1><p>Practical, local guidance for grooming, coat care, daycare, and helping your pet feel ready for a visit.</p></section><section class="blog-grid">${blogs.map(blog=>`<article class="blog-card"><p class="tag">Petssible journal</p><h2>${esc(blog.title)}</h2><p>${esc(blog.desc)}</p><a class="text-link" href="${blog.slug}.html">Read the guide &#8594;</a></article>`).join('')}</section></main>`}); }
function blogPage(blog) { return shell({depth:1,title:blog.meta,description:blog.desc,pagePath:`blog/${blog.slug}.html`,extra:{'@type':'BlogPosting',headline:blog.title,description:blog.desc,author:{'@type':'Organization',name:business.short},publisher:{'@type':'Organization',name:business.short}},body:`<main><section class="subhero"><p class="crumb"><a href="../index.html">Home</a> / <a href="index.html">Blog</a> / Guide</p><h1>${esc(blog.title)}</h1><p>${esc(blog.desc)}</p></section><article class="blog-article"><p class="tag">Petssible journal</p>${blog.body}<div class="blog-call"><h2>Questions about your pet's next visit?</h2><p>Call Petssible at ${business.phone}, or request a preferred time online.</p><a class="button orange" href="../index.html#reservation">Get a quote</a></div></article></main>`}); }
function write(relative,content) { const file=path.join(out,relative); fs.mkdirSync(path.dirname(file),{recursive:true}); fs.writeFileSync(file,content); }
fs.rmSync(out,{recursive:true,force:true}); fs.mkdirSync(out,{recursive:true});
const assets=path.resolve(__dirname,'..','..','outputs','petssible-hero','assets'); fs.cpSync(assets,path.join(out,'assets'),{recursive:true});
const realPhotoRoot=path.resolve(__dirname,'..','petssible-photo-review','Petssible');
[['PHOTO-2026-05-04-18-24-52.JPG','petssible-groomed-poodle.jpg'],['PHOTO-2026-07-17-12-14-11.JPG','petssible-groomed-spaniel.jpg'],['PHOTO-2026-07-28-13-54-08.JPG','petssible-groomed-pomeranian.jpg'],['PHOTO-2026-06-16-11-07-15.JPG','petssible-groomed-terrier.jpg']].forEach(([source,target])=>fs.copyFileSync(path.join(realPhotoRoot,source),path.join(out,'assets',target)));
write('index.html',home()); write('index.md',markdown('Petssible Pet Grooming in El Paso',business.description,''));
write('services/index.html',listing('services')); write('services/index.md',markdown('Petssible Services','Pet grooming and care services in El Paso.','services/'));
services.forEach(s=>{write(`services/${s.slug}.html`,servicePage(s));write(`services/${s.slug}.md`,markdown(s.h1,s.desc,`services/${s.slug}.html`));});
write('service-areas/index.html',listing('areas')); write('service-areas/index.md',markdown('Petssible Service Areas','Service-area pages for Petssible.','service-areas/'));
areas.forEach(a=>{write(`service-areas/${a.slug}.html`,areaPage(a));write(`service-areas/${a.slug}.md`,markdown(a.h1,`Pet grooming for pet parents near ${a.name}.`,`service-areas/${a.slug}.html`));});
write('blog/index.html',blogIndex()); write('blog/index.md',markdown('Pet Grooming Tips in El Paso','Helpful grooming, daycare, and coat-care guides from Petssible.','blog/'));
blogs.forEach(blog=>{write(`blog/${blog.slug}.html`,blogPage(blog));write(`blog/${blog.slug}.md`,markdown(blog.title,blog.desc,`blog/${blog.slug}.html`));});
write('site.css',fs.readFileSync(path.join(__dirname,'site.css'),'utf8')); write('enhancements.css',fs.readFileSync(path.join(__dirname,'enhancements.css'),'utf8')); write('mobile.css',fs.readFileSync(path.join(__dirname,'mobile.css'),'utf8')); write('calendar.css',fs.readFileSync(path.join(__dirname,'calendar.css'),'utf8')); write('original-tuning.css',fs.readFileSync(path.join(__dirname,'original-tuning.css'),'utf8')); write('blog.css',fs.readFileSync(path.join(__dirname,'blog.css'),'utf8')); write('quote.css',fs.readFileSync(path.join(__dirname,'quote.css'),'utf8')); write('stickers.css',fs.readFileSync(path.join(__dirname,'stickers.css'),'utf8')); write('site.js',fs.readFileSync(path.join(__dirname,'site.js'),'utf8'));
const urls=['','services/','service-areas/','blog/',...services.map(s=>`services/${s.slug}.html`),...areas.map(a=>`service-areas/${a.slug}.html`),...blogs.map(blog=>`blog/${blog.slug}.html`)];
write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${business.domain}/${u}</loc></url>`).join('')}</urlset>`);
write('robots.txt',`User-agent: *\nAllow: /\n\nSitemap: ${business.domain}/sitemap.xml\n`);
write('llms.txt',`# Petssible\n\n${business.description}\n\nAddress: ${business.street}, ${business.city}, ${business.state} ${business.zip}\nPhone: ${business.phone}\nRating: ${business.rating}/5 from ${business.reviewCount} Google reviews\n\n## Services\n${services.map(s=>`- [${s.name}](${business.domain}/services/${s.slug}.html)`).join('\n')}\n\n## Service areas\n${areas.map(a=>`- [${a.name}](${business.domain}/service-areas/${a.slug}.html)`).join('\n')}\n`);
write('NOTES-CONFIRM.md',`# Confirm before launch\n\n- Canonical domain is set to ${business.domain}, based on the supplied URL. Confirm it is the final domain for the rebuilt site.\n- Hours are set to ${business.hours}, based on the current website. Confirm they are current.\n- No lead webhook or booking endpoint is connected. Buttons call the business phone number only.\n- Rating (${business.rating}) and review count (${business.reviewCount}) came from the supplied Google Business Profile text. The six displayed review excerpts were copied from the supplied attachment.\n- Service-area pages describe customers visiting the El Paso location. Confirm the final list of communities before launch.\n`);
require('./enhance.cjs')(out);
console.log(`Generated ${1+2+services.length+areas.length} HTML content pages in ${out}`);
